#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	cat <<EOF > "${MODULE_SRCDIR}/make.inc"
PLAT		= 
SuperLUroot 	= \${PREFIX}
SUPERLULIB   	= \$(SuperLUroot)/lib/libsuperlu.a
BLASDEF	     	= -DUSE_VENDOR_BLAS
BLASLIB      	= \${OPENBLAS_PREFIX}/lib/libopenblas.a
TMGLIB          = libtmglib.a
METISLIB	=
PARMETISLIB	=
FLIBS	 	= 
LIBS            = \$(DSUPERLULIB) \$(BLASLIB) \$(PARMETISLIB) \$(METISLIB)
ARCH         	= ar
ARCHFLAGS    	= cr
RANLIB       	= ranlib
CC           	= ${CC}
CFLAGS          = -pipe -O3
NOOPTS		= 
FORTRAN         = ${FC}
F90FLAGS	= 
LOADER	        = ${FC}
LOADOPTS	= -fopenmp 
CDEFS        = -DAdd_ 
EOF
}

pmodules.build() {
	cd "${MODULE_SRCDIR}"
	mkdir -p "${PREFIX}/lib"
	make
}

pmodules.install() {
	make install
	mkdir -p "${PREFIX}/include"
	install -m 0444 "${MODULE_SRCDIR}"/SRC/*.h "${PREFIX}/include"
}

pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies "${COMPILER}" 'OpenBLAS'
pmodules.set_docfiles 'README'
pmodules.make_all
pmodules.cleanup_src
