#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	cd "${MODULE_SRCDIR}"
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-tcltk \
		|| exit 1
}

pmodules.build() {
        cd "${MODULE_SRCDIR}"
        make
}

pmodules.add_to_group 'Tools'
pmodules.set_runtime_dependencies 'Tcl' 'Tk'
pmodules.set_docfiles 'COPYING' 'README'
pmodules.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
