#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	(cd "${MODULE_SRCDIR}" && ./autogen.sh)
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-debug \
		--enable-vtkconverter \
		--with-hdf5="${HDF5_SERIAL_PREFIX}" \
		--with-pic \
		|| exit 1
}

pmodules.build() {
	make -C src
	make -C tools 
}

pmodules.install() {
	make -C src install
	make -C tools install
}

pmodules.add_to_group 'HDF5_serial'
pmodules.set_runtime_dependencies "${COMPILER}" 'hdf5_serial'
pmodules.set_build_dependencies   "autoconf" "automake" "libtool" "${COMPILER}" "vtk" "hdf5_serial"
pmodules.make_all

