#!/bin/bash

source $(dirname $0)/../../../lib/libpmodules.bash

pmodules.pre_configure() {
	./autogen.sh
}

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-h5hut \
		--enable-hdf5 \
		--enable-root \
		--with-pic
}

pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}" 'hdf5_serial' 'root'
pmodules.set_build_dependencies 'autoconf' 'automake' 'libtool' "${COMPILER}" 'hdf5_serial' 'H5hut_serial' 'root'
pmodules.make_all

