#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN

	rm -f CMakeCache.txt
	cmake \
		-DCMAKE_BUILD_TYPE=RELEASE \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		"${MODULE_SRCDIR}" \
		|| exit 1 
}

pmodules.add_to_group 'MPI'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}"
pmodules.set_build_dependencies 'cmake' "${COMPILER}" "${MPI}"
pmodules.set_docfiles LICENSE README
pmodules.make_all

