#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}/bootstrap" --prefix="${PREFIX}"
}

pmodules.add_to_group 'Programming'
pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all

