---
# yamllint disable rule:line-length
format: 1
libxsmm:
  defaults:
    group: Libraries
    overlay: base
    relstage: stable
    urls:
      - url: https://github.com/${P}/${P}/archive/refs/tags/${V_PKG}.tar.gz

  shasums:
    2.1.0.tar.gz: 704ed8f99b61a767798ed1ee1cadc5d185ca449f466a2bae37930f68c65961e9

  versions:
    2.1.0:
      variants:
        - overlay: base
          target_cpus: [x86_64]
          systems: [.*.merlin7.psi.ch]
          relstage: stable
          configure_with: cmake
          build_requires:
            - gcc/13.4.0
          runtime_deps:
            - gcc/13.4.0
        - overlay: base
          target_cpus: [aarch64]
          systems: [gpu0.*.merlin7.psi.ch]
          relstage: stable
          configure_with: cmake
          build_requires:
            - gcc/13.4.0
          runtime_deps:
            - gcc/13.4.0
