#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-mpi-cxx \
		--enable-mpi-cxx-seek \
		--enable-mpi-f90 \
		--enable-mpi-profile \
		--enable-shared \
		--enable-smp-locks \
		|| exit 1
}


pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies "${COMPILER}"
pmodules.set_docfiles 'AUTHORS' 'LICENSE' 'NEWS' 'README'
pmodules.make_all
