#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	cmake \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		-DCMAKE_BUILD_TYPE=RELEASE \
		-DGMX_MPI=on \
		-DGMX_GPU=off \
		-DGMX_BUILD_OWN_FFTW=on \
		"${MODULE_SRCDIR}" \
		|| exit 1
}


pmodules.add_to_group 'MPI'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}"
pmodules.set_build_dependencies "${COMPILER}" "${MPI}" cmake
pmodules.set_docfiles \
		AUTHORS \
		COPYING \
		README
pmodules.make_all

