#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	:
}

pmodules.build() {
	:
}

pmodules.install() {
	cd "${MODULE_SRCDIR}"
	rsync --exclude=".info" --delete --verbose --archive . "${PREFIX}"
}

pmodules.add_to_group 'Programming'
pmodules.make_all
