#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.pre_configure() {
	:
}

pmodules.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-netcdf-4 \
		--with-pic \
		|| exit 1
}

pmodules.add_to_group 'HDF5'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}" 'hdf5'
pmodules.set_build_dependencies   "${COMPILER}" "${MPI}" 'hdf5'
pmodules.set_docfiles 'COPYRIGHT' 'README.md' 'RELEASE_NOTES.md'
pmodules.make_all

