#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc

pmodules.add_to_group 'Programming'
pmodules.set_docfiles 'AUTHORS' 'COPYING' 'NEWS' 'README' 'THANKS'
pmodules.set_build_dependencies 'autoconf' 'automake'
pmodules.make_all

