#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.pre_configure() {
	./autogen.sh
}

pmodules.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN
	#( cd "${MODULE_SRCDIR}" && ./autogen.sh )
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-parallel \
		--enable-debug \
		--with-hdf5=$HDF5_PREFIX \
		--with-pic \
		|| exit 1
}

pmodules.build() {
	make -C src
	make -C tools 
}

pmodules.install() {
	make -C src install
	make -C tools install
}


pmodules.add_to_group 'HDF5'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}" 'hdf5'
pmodules.set_build_dependencies   "autoconf" "automake" "libtool" "${COMPILER}" "${MPI}" "hdf5"
pmodules.set_docfiles 'AUTHORS' 'COPYING'
pmodules.make_all

