#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-languages=c,c++,objc,obj-c++,lto,fortran \
		--with-gmp="${GMP_PREFIX}" \
		--with-mpfr="${MPFR_PREFIX}" \
		--with-mpc="${MPC_PREFIX}" \
		--enable-lto \
		--disable-multilib \
		--with-pkgversion="PSI Environment Module" \
		|| exit 1
}


# use system gcc to compile
declare -rx CC=gcc
declare -rx CXX=g++

module use 'Libraries'
pmodules.add_to_group 'Programming'
pmodules.set_build_dependencies 'gmp' 'mpfr' 'mpc'
pmodules.set_docfiles 'COPYING' 'COPYING.LIB' 'COPYING.RUNTIME' 'COPYING3' 'COPYING3.LIB' 'NEWS' 'README'
pmodules.make_all

