#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	unset F90
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-cxx \
		--enable-fortran \
		|| exit 1
}


pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies "${COMPILER}"
pmodules.set_docfiles 'COPYRIGHT' 'README'
pmodules.make_all
