---
format: 1
squashfuse:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    systems: [.*]
    docfiles:
      - CONFIGURATION
      - LICENSE
      - NEWS
      - PLATFORMS
      - README
      - TODO
    urls:
      - url: https://github.com/vasi/$P/releases/download/${V_PKG}/$P-${V_PKG}.tar.gz

  shasums:
    squashfuse-0.6.1.tar.gz: 7b18a58c40a3161b5c329ae925b72336b5316941f906b446b8ed6c5a90989f8c

  versions:
    0.6.1:
      config:
        configure_args: [CC=gcc]
