#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	CC=$MPICC CXX=$MPICXX cmake \
		-DCMAKE_INSTALL_PREFIX="${PREFIX}" \
		-DCMAKE_BUILD_TYPE=RELEASE \
		"${MODULE_SRCDIR}"
}

pmodules.add_to_group 'MPI'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}"
pmodules.set_build_dependencies 'cmake' "${COMPILER}" "${MPI}"
pmodules.set_docfiles 'license.txt' 'README.txt'
pmodules.make_all


