---
format: 1
bats:
  defaults:
    group: Tools
    overlay: base
    relstage: stable
    systems: [.*]
    docfiles:
      - AUTHORS
      - LICENSE.md
      - README.md
      - SECURITY.md
    urls:
      - url: https://github.com/bats-core/bats-core/archive/refs/tags/v${V_PKG}.tar.gz
        name: bats-${V_PKG}.tar.gz
  shasums:
  versions:
    1.13.0:
      config:
