#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		|| exit 1
}

pmodules.add_to_group 'Libraries'
pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all
