#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	cd "${MODULE_SRCDIR}"
	./configure \
		--prefix="${PREFIX}" \
		--with-libpcap=included \
		--with-libpcre=included \
		--with-libdnet=included \
		--with-liblua=included \
		--with-liblinear=included
}

pmodules.build() {
	cd "${MODULE_SRCDIR}"
	make -j "${JOBS}"
}

pmodules.install() {
	cd "${MODULE_SRCDIR}"
	make install
}

pmodules.add_to_group 'System'
pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all
