format: 1
xpmem:
  defaults:
    group: Libraries
    relstage: stable
    compile_in_sourcetree: true
    configure_args:
      - --enable-shared
      - --enable-static
    docfiles:
      - COPYING
      - INSTALL
      - NEWS
      - README
    urls:
      - url: https://github.com/hpc/xpmem/archive/refs/tags/v${V_PKG}.tar.gz
        name: xpmem-${V_PKG}.tar.bz2
  shasums:
    pmix-5.0.10.tar.gz: 7c0be0b5f85cc605fc51b44642fab72494e739ef9c1aa52a8741b847d6907b43
  versions:
    2.6.5:
      config:
        relstage: unstable
        group_deps:
          compiler: {gcc: [15.2.0]}
        configure_args+:
          - --disable-kernel-module
      variants:
        - systems: [.*.merlin7.psi.ch]
          overlay: Alps
          use_overlays: [PSI]
        - systems: [merlin-.*]
          relstage: unstable
          overlay: base
