#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-gmp=$GMP_PREFIX \
		--disable-shared \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc

module use 'Libraries'

pmodules.add_to_group 'Libraries'
pmodules.set_build_dependencies 'gmp'
pmodules.make_all
