#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-shared \
		--enable-cxx \
		--enable-unsupported \
		--with-pic \
		|| exit 1
}

pmodules.add_to_group 'Compiler'
pmodules.set_runtime_dependencies "${COMPILER}"
pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all

