#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--disable-shared \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc
declare -rx CPP=/usr/bin/cpp

pmodules.add_to_group 'Libraries'
pmodules.make_all

