---
# yamllint disable rule:line-length
format: 1
libxs:
  defaults:
    group: Compiler
    overlay: base
    relstage: stable
    urls:
      - url: https://github.com/hfp/${P}/archive/refs/tags/${V_PKG}.tar.gz

  shasums:
    1.0.0.tar.gz: b26654a9d7d41e7281a785d3674626c2484c92e7fc698e166639c8e78b2b18ee

  versions:
    1.0.0:
      variants:
        - systems: [login.*.merlin7.psi.ch, cn.*.merlin7.psi.ch]
          target_cpus: [x86_64]
          relstage: stable
          configure_with: cmake
          overlay: base
          use_overlays: [PSI]
          group_deps:
            compiler: { gcc: [13.4.0] }
        - systems: [gpu0.*.merlin7.psi.ch]
          target_cpus: [aarch64]
          relstage: stable
          configure_with: cmake
          overlay: base
          use_overlays: [PSI]
          group_deps:
            compiler: { gcc: [13.4.0] }

