#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		|| exit 1
}

# use system gcc to compile
declare -rx CC=gcc

pmodules.add_to_group 'Programming'
pmodules.set_docfiles \
	AUTHORS \
	COPYING \
	ChangeLog \
	HACKING \
	NEWS \
	README \
	THANKS
pmodules.set_build_dependencies 'm4' 'autoconf'
pmodules.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:

