#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-pic=yes \
		--with-included-ltdl \
		|| exit 1
}

pmodules.add_to_group 'Tools'
pmodules.set_docfiles 'AUTHORS' 'COPYING' 'COPYING.LIB' 'LICENSE' 'README' 'THANKS'
pmodules.set_build_dependencies "gcc/4.8.3"
pmodules.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
