#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	:
}

pmodules.build() {
        cd "${MODULE_SRCDIR}"

	make -j ${JOBS}
}

pmodules.install() {
        cd "${MODULE_SRCDIR}"
	mkdir -p ${PREFIX}/bin
	install -m 0755 mdtest "${PREFIX}/bin"
}

#pmodules.supported_os 'Linux'
pmodules.add_to_group 'System'
pmodules.set_build_dependencies "${COMPILER}" "${MPI}"
pmodules.make_all
