#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.add_to_group 'Programming'
pmodules.set_runtime_dependencies ""
pmodules.set_build_dependencies   "${COMPILER}"
pmodules.make_all

