#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	CC=$MPICC
	CXX=$MPICXX
	F77=$MPIF77
	F90=$MPIF90
	FC=$MPIFC
	FORTRAN=$MPIFORTRAN

	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--enable-shared \
		--enable-parallel \
		--enable-cxx \
		--enable-unsupported \
		--with-pic \
		|| exit 1
}


pmodules.add_to_group 'MPI'
pmodules.set_runtime_dependencies "${COMPILER}" "${MPI}"
pmodules.set_build_dependencies "${COMPILER}" "${MPI}"
pmodules.set_docfiles \
		ACKNOWLEDGMENTS \
		COPYING \
		MANIFEST \
		README.txt
pmodules.make_all

