#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	:
}

pmodules.build() {
	cd "${MODULE_SRCDIR}"
	make
}

pmodules.install() {
	cd "${MODULE_SRCDIR}"
	install -m 0755 -d "${PREFIX}/bin"
	install -m 0755 unison "${PREFIX}/bin"
}

pmodules.add_to_group 'System'
pmodules.set_docfiles 'BUGS.txt' 'CONTRIB' 'COPYING' 'NEWS' 'README'
#pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
