#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		--with-gif=no \
		--with-tiff=no \
		|| exit 1
}

pmodules.add_to_group 'Tools'
pmodules.set_docfiles 'Copyright' 'ChangeLog' 'NEWS' 'README'
pmodules.set_build_dependencies "${COMPILER}"
pmodules.make_all

# Local Variables:
# mode: sh
# sh-basic-offset: 8
# tab-width: 8
# End:
