#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
    "${MODULE_SRCDIR}"/configure \
		      --prefix="${PREFIX}" \
	|| exit 1
}

pmodules.add_to_group 'Tools'
pmodules.make_all
