#!/bin/bash

source "$(dirname $0)/../../../lib/libpmodules.bash"

pmodules.configure() {
	"${MODULE_SRCDIR}"/configure \
		--prefix="${PREFIX}" \
		|| exit 1
}

pmodules.post_install() {
	ln -fs "${PREFIX}/bin/python${V%%.*}" "${PREFIX}/bin/python"
	ln -fs "${PREFIX}/include/python${V%.*}m" "${PREFIX}/include/python"
	ln -fs "${PREFIX}/include/python${V%.*}m" "${PREFIX}/include/python${V%.*}"
}

pmodules.add_to_group 'Programming'
pmodules.set_runtime_dependencies ""
pmodules.set_build_dependencies   "${COMPILER}"
pmodules.make_all

